# Generated by Django 4.2.5 on 2025-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constraints',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('faculty', models.CharField(blank=True, max_length=20, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('building', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'constraints',
            },
        ),
    ]
