# Generated by Django 5.1.7 on 2025-06-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0002_user_stuff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('building', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'audience',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=255)),
                ('activity_type_name', models.CharField(max_length=255)),
                ('semester', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('grp', models.CharField(max_length=255)),
                ('teacher', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'lessons',
            },
        ),
    ]
