# Generated by Django 5.1.7 on 2025-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ares', '0003_audience_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='grp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
